Updated documentation to include expected payload type.
spring-cloud-stream-app-starters/tasklauncher-local pull request #4
Opened 2017-08-10 21:44 UTC by cppwfs

2017-08-11 12:35 UTC, artembilan requested changes

2017-08-11 12:35 UTC, artembilan commented on spring-cloud-starter-stream-sink-task-launcher-local/README.adoc
> +* `org.springframework.cloud.task.launcher.TaskLaunchRequest`
Is there any confirmation that this one can be (de)serialized to/from JSON?
Doesn't look persuasively to use this kind of data in between Microservices...

2017-08-11 13:17 UTC, cppwfs commented on spring-cloud-starter-stream-sink-task-launcher-local/README.adoc
> +* `org.springframework.cloud.task.launcher.TaskLaunchRequest`
We have tested the task-launchers using triggertask or  transformers which produce TaskLaunchRequests.

2017-08-11 13:25 UTC, artembilan commented on spring-cloud-starter-stream-sink-task-launcher-local/README.adoc
> +* `org.springframework.cloud.task.launcher.TaskLaunchRequest`
Good. Was there a test when this `TaskLaunchRequest` is sent/received as JSON or only serialization variants?

2017-08-24 23:06 UTC, sobychacko commented
Merging as the review comments are addressed.

2017-08-24 23:06 UTC, closed without merging